### ISSUE TITLE
What are the boundaries of the identity system?

### ISSUE THREAD

**Issue by devinhalladay** [GD399-OSD/public-domain#2]
Here's an inventory of the important elements of the identity:
- Grid
- Line
- Type
- Photo
- "Standard" sizes and grids
- Logo

All of these pieces should be considered relatively flexible. But I need limits.

The grid should be imposed as much as possible as a guide for composition, but only in communications produced *by* Public Domain. Things produced by end-users of the identity system do not need to obey the grid this strictly. `Is this double standard problematic/overcomplicated???`

Line should be used in only two ways:
1. To indicate structural division (i.e. to aid in hierarchical composition)
2. To indicate interconnection (i.e. as a graphic element)

Type should be standarized. The identity should use only two typefaces primarily, unless a context demands a radical shift in type choice. These typefaces must be open source. The serif is Spectral, and the sans-serif is still undefined. Currently I am using Favorit, but that is not open-source.

Photos should be used liberally, in a bold manner, and with a critical voice. Images should be used to establish interesting, unexpected, or critical connections between cultures, subcultures, artifacts, aesthetics, and ideas. When using the logomark as a container for images and videos, we should be very careful with the implication of having the subjects of the image labeled as being in the "Public Domain". i.e. if an image of a person or group of people is contained in the logo, labeling those people as "Public Domain" is potentially very problematic. `How do I solve this?`

Standard page sizes and grids are to be used whenever possible to make it easy to reproduce/reprint collateral and to ease the barrier to entry into the identity system's usage.

**Comment by devinhalladay** [comment]
With those boundaries out of the way, the remaining task to tackle is the boundaries of applying the logo.

**Comment by bjornmeansbear** [comment]
Perhaps the idea of a grid is just that, that there is an idea of a grid? is it important that everyone use the same grid? is it important that everyone understand what a grid is for? if the Public Domain communications must use it, but other potential uses might not does that create a conflict in brand standards? how might that be mitigated?

**Comment by devinhalladay** [comment]
Whoa, great thinking @bjornmeansbear! That's killer. That makes me think, maybe instead of making "grid" part of the brand guidelines, I need to make "composition" a part.  Composition is a much looser term and I think might be moe accessible to end-users (i.e. people not trained in design).

**Comment by devinhalladay** [comment]
The answer for now: **fuck it**.

I'll figure this bit out later. Closing this issue for now so I can get out of my damn head and start making real shit.
